dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run build
  # these two cat commands are for debug only while angular/angular#15192 is not fixed
  - cat typings/angular-quickstart-lib.d.ts
  - cat typings/angular-quickstart-lib.metadata.json
  - cd e2e-app/
  - npm install
  - npm run e2e
  - npm run e2e:aot
